services:
  indexer:
    image: oasislabs/oasis-indexer:dev
    depends_on:
      postgres:
        condition: service_healthy
      oasis-node:
        condition: service_healthy
    ports:
      - 8008:8008
    command:
      - --config=/config/docker-dev.yml
    volumes:
      - type: bind
        source: ./docker/node
        target: /node
      - type: bind
        source: ./storage/migrations
        target: /storage/migrations
      - type: bind
        source: ./config
        target: /config
  postgres:
    image: postgres:13.7
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indexer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indexer"]
      interval: 5s
      retries: 10
      timeout: 5s
      start_period: 15s
  oasis-node:
    image: oasislabs/oasis-node:dev
    user: oasis
    command:
      - /bin/sh
      - -c
      - oasis-node --config /node/etc/config.yml
    volumes:
      - type: bind
        source: ./docker/node
        target: /node
    healthcheck:
      test: oasis-node control status -a unix:/node/data/internal.sock || exit 1
      interval: 5s
      retries: 10
      timeout: 5s
      start_period: 30s
  oasis-net-runner:
    image: oasisprotocol/oasis-net-runner:dev
    volumes:
      - type: bind
        source: ./
        target: /oasis-indexer
    command:
      - /bin/sh
      - -c
      - oasis-net-runner --basedir.no_temp_dir --basedir /testnet --fixture.default.node.binary oasis-node --fixture.default.setup_runtimes=false --fixture.default.deterministic_entities=true --fixture.default.fund_entities --fixture.default.num_entities 2
    security_opt:
      - apparmor:unconfined
      - seccomp=unconfined
    working_dir: /code

volumes:
  config: {}
  go: {}
  migrations: {}
