services:
  nexus:
    image: oasislabs/oasis-indexer:${USER}-dev
    container_name: nexus
    depends_on:
      nexus-postgres:
        condition: service_healthy
      oasis-node:
        condition: service_healthy
    ports:
      - 8008:8008
    command:
      - --config=/config/docker-dev.yml
    volumes:
      - type: bind
        source: ./docker/node
        target: /node
      - type: bind
        source: ./storage/migrations
        target: /storage/migrations
      - type: bind
        source: ./config
        target: /config
  nexus-postgres:
    image: postgres:13.7
    container_name: nexus-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rwuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indexer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rwuser -d indexer"]
      interval: 5s
      retries: 10
      timeout: 5s
      start_period: 15s
  oasis-node:
    image: oasislabs/oasis-node:${USER}-dev
    container_name: oasis-node
    user: oasis
    command:
      - /bin/sh
      - -c
      - oasis-node --config /node/etc/config.yml
    volumes:
      - type: bind
        source: ./docker/node
        target: /node
    healthcheck:
      test: oasis-node control status -a unix:/node/data/internal.sock || exit 1
      interval: 5s
      retries: 10
      timeout: 5s
      start_period: 30s

volumes:
  config: {}
  go: {}
  migrations: {}
