analysis:
  source:
    chain_name: mainnet
    nodes:
      eden:
        default:
          rpc: unix:/tmp/node.sock #unix:/node/data/internal.sock
    ipfs:
      gateway: https://ipfs.io
  analyzers:
    metadata_registry:
      interval: 1h
    aggregate_stats: {}
    consensus:
      from: 16_817_956  # Eden genesis
    emerald:
      from: 7_875_129  # round at Eden genesis
    sapphire:
      from: 1_357_486  # round at Eden genesis
  storage:
    backend: postgres
    endpoint: postgresql://rwuser:password@nexus-postgres:5432/indexer?sslmode=disable
    migrations: file://storage/migrations

server:
  source:
    chain_name: mainnet
  endpoint: 0.0.0.0:8008
  storage:
    endpoint: postgresql://rwuser:password@nexus-postgres:5432/indexer?sslmode=disable
    backend: postgres

log:
  level: debug
  format: json

metrics:
  pull_endpoint: 0.0.0.0:8009
