analysis:
  source:
    chain_name: mainnet
    nodes:
      damask:
        default:
          rpc: unix:/tmp/node.sock #unix:/node/data/internal.sock
  analyzers:
    metadata_registry:
      interval: 1h
    aggregate_stats: {}
    consensus:
      from: 8_048_956  # Damask genesis
    emerald:
      from: 1_003_298  # round at Damask genesis
    sapphire:
      from: 0  # first round in Damask
  storage:
    backend: postgres
    endpoint: postgresql://rwuser:password@nexus-postgres:5432/indexer?sslmode=disable
    migrations: file://storage/migrations

server:
  chain_name: mainnet
  endpoint: 0.0.0.0:8008
  storage:
    endpoint: postgresql://rwuser:password@nexus-postgres:5432/indexer?sslmode=disable
    backend: postgres

log:
  level: debug
  format: json

metrics:
  pull_endpoint: 0.0.0.0:8009
