analysis:
  source:
    chain_name: mainnet
    nodes: &src
      eden:
        default:
          rpc: unix:/tmp/node.sock #unix:/node/data/internal.sock
    ipfs:
      gateway: https://ipfs.io
  analyzers:
    metadata_registry:
      interval: 1h
    node_stats: {}
    aggregate_stats: {}
    consensus:
      from: 16_817_956  # Eden genesis
    emerald:
      from: 7_875_129  # round at Eden genesis
    sapphire:
      from: 1_357_486  # round at Eden genesis
  storage:
    backend: postgres
    endpoint: postgresql://rwuser:password@localhost:5432/indexer?sslmode=disable
    migrations: file://storage/migrations

server:
  chain_name: mainnet
  endpoint: localhost:8008
  storage:
    endpoint: postgresql://rwuser:password@localhost:5432/indexer?sslmode=disable
    backend: postgres
  source:
    chain_name: mainnet
    nodes: *src

log:
  level: info
  format: json

metrics:
  pull_endpoint: localhost:8009
