analysis:
  source:
    chain_name: mainnet
    nodes:
      damask:
        rpc: unix:/tmp/node.sock #unix:/node/data/internal.sock
  analyzers:
    metadata_registry:
      interval: 1h
    aggregate_stats:
      tx_volume_interval: 10m
    consensus:
      from: 8_048_956  # Damask genesis
    emerald:
      from: 1_003_298  # round at Damask genesis
    sapphire:
      from: 0  # first round in Damask
  storage:
    backend: postgres
    endpoint: postgresql://rwuser:password@localhost:5432/indexer?sslmode=disable
    migrations: file://storage/migrations

server:
  chain_name: mainnet
  endpoint: localhost:8008
  storage:
    endpoint: postgresql://rwuser:password@localhost:5432/indexer?sslmode=disable
    backend: postgres

log:
  level: info
  format: json

metrics:
  pull_endpoint: localhost:8009
